---
-  hosts: ec2
   connection: local
   tasks:
   - name: ProvisionEC2box
     ec2: 
       image: ami-0cd3dfa4e37921605
       instance_type: t2.micro
       keypair: bikash_devops_key
       vpc_subnet_id: subnet-0f462475
       region: us-east-2
       count: 1
